# Generated by Django 2.2.2 on 2019-06-21 23:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20190619_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('flight_number',
                 models.CharField(max_length=100,
                                  verbose_name='Flight number')),
                ('seat', models.CharField(max_length=100,
                                          verbose_name='Seat')),
                ('date_made',
                 models.DateTimeField(auto_now_add=True,
                                      verbose_name='Date made')),
                ('made_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='reservation',
                                   to='user.User')),
            ],
            options={
                'verbose_name_plural': 'Reservations',
                'db_table': 'fl_reservations',
            },
        ),
    ]
