# Generated by Django 2.2.2 on 2019-06-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booked',
            field=models.BooleanField(default=False,
                                      verbose_name='Has been Booked'),
        ),
    ]
