# Generated by Django 2.2.2 on 2019-06-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_reservation_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='take_off',
        ),
    ]
