# Generated by Django 2.2.2 on 2019-06-21 11:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('model',
                 models.CharField(max_length=100,
                                  null=True,
                                  verbose_name='Plane model')),
                ('grounded',
                 models.BooleanField(default=False,
                                     verbose_name='Is Grounded')),
                ('seats',
                 django.contrib.postgres.fields.jsonb.JSONField(
                     verbose_name='Seats')),
            ],
            options={
                'verbose_name_plural': 'Planes',
                'db_table': 'fl_planes',
            },
        ),
    ]
