# Generated by Django 2.2.2 on 2019-06-21 20:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20190621_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('flight_number',
                 models.CharField(max_length=100,
                                  null=True,
                                  verbose_name='Flight number')),
                ('price',
                 models.DecimalField(decimal_places=2,
                                     max_digits=11,
                                     verbose_name='Price')),
                ('take_off',
                 models.CharField(max_length=100,
                                  null=True,
                                  verbose_name='Take off')),
                ('destination',
                 models.CharField(max_length=100,
                                  null=True,
                                  verbose_name='Destination')),
                ('date', models.DateField(verbose_name='Date')),
                ('departure_time',
                 models.TimeField(verbose_name='Departure Time')),
                ('arrival_time',
                 models.TimeField(verbose_name='Arrival Time')),
                ('plane',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='flight',
                                   to='flight.Plane')),
            ],
            options={
                'verbose_name_plural': 'Flights',
                'db_table': 'fl_flights',
            },
        ),
    ]
