# Generated by Django 2.2.2 on 2019-06-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seats',
            old_name='number',
            new_name='seat_number',
        ),
    ]
