# Generated by Django 2.2.2 on 2019-06-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_auto_20190623_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='model',
            field=models.CharField(default='dummy',
                                   max_length=100,
                                   verbose_name='Plane model'),
            preserve_default=False,
        ),
    ]
