# Generated by Django 2.2.2 on 2019-06-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_auto_20190624_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(default='ECO',
                                   max_length=100,
                                   verbose_name='Destination'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(default='ECO',
                                   max_length=100,
                                   unique=True,
                                   verbose_name='Flight number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='take_off',
            field=models.CharField(default='ECO',
                                   max_length=100,
                                   verbose_name='Take off'),
            preserve_default=False,
        ),
    ]
