# Generated by Django 2.2.3 on 2019-07-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_auto_20190625_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'),
                                            ('Departed', 'Departed'),
                                            ('Ready to leave',
                                             'Ready to leave')],
                                   default='Pending',
                                   max_length=100,
                                   verbose_name='Status'),
        ),
    ]
