# Generated by Django 2.2.3 on 2019-07-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_flight_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'),
                                            ('Departed', 'Departed'),
                                            ('Ready', 'Ready to leave')],
                                   default='Pending',
                                   max_length=100,
                                   verbose_name='Status'),
        ),
    ]
