# Generated by Django 2.2.2 on 2019-06-17 15:01

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password',
                 models.CharField(max_length=128, verbose_name='password')),
                ('last_login',
                 models.DateTimeField(blank=True,
                                      null=True,
                                      verbose_name='last login')),
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('email',
                 models.EmailField(max_length=255,
                                   unique=True,
                                   verbose_name='Email')),
                ('first_name',
                 models.CharField(blank=True,
                                  max_length=255,
                                  verbose_name='First Name')),
                ('middle_name',
                 models.CharField(blank=True,
                                  max_length=255,
                                  verbose_name='Middle Name')),
                ('last_name',
                 models.CharField(blank=True,
                                  max_length=255,
                                  verbose_name='Last Name')),
                ('is_active',
                 models.BooleanField(default=True, verbose_name='Is active')),
                ('is_staff',
                 models.BooleanField(default=False, verbose_name='Is staff')),
                ('is_superuser',
                 models.BooleanField(default=False,
                                     verbose_name='Superuser status')),
                ('verification_token',
                 models.CharField(blank=True,
                                  max_length=100,
                                  null=True,
                                  verbose_name='verification token')),
                ('password_reset',
                 models.CharField(blank=True,
                                  max_length=100,
                                  null=True,
                                  verbose_name='Password reset token')),
                ('is_verified',
                 models.BooleanField(default=False,
                                     verbose_name='Is verified')),
                ('date_joined',
                 models.DateTimeField(default=django.utils.timezone.now,
                                      verbose_name='Date joined')),
                ('gender',
                 models.CharField(choices=[('M', 'Male'), ('F', 'Female'),
                                           ('None', 'None')],
                                  default=None,
                                  max_length=10,
                                  null=True,
                                  verbose_name='Gender')),
                ('dob',
                 models.DateField(null=True, verbose_name='Date of Birth')),
                ('seat_preference',
                 models.CharField(choices=[('Window', 'Window seat'),
                                           ('Aisle', 'Aisle seat')],
                                  default=None,
                                  max_length=10,
                                  null=True,
                                  verbose_name='Seat Preference')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
