# Generated by Django 2.2.2 on 2019-06-19 09:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20190619_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('first_name',
                 models.CharField(blank=True,
                                  max_length=255,
                                  verbose_name='First Name')),
                ('middle_name',
                 models.CharField(blank=True,
                                  max_length=255,
                                  verbose_name='Middle Name')),
                ('last_name',
                 models.CharField(blank=True,
                                  max_length=255,
                                  verbose_name='Last Name')),
                ('gender',
                 models.CharField(choices=[('M', 'Male'), ('F', 'Female'),
                                           ('None', 'None')],
                                  default=None,
                                  max_length=10,
                                  null=True,
                                  verbose_name='Gender')),
                ('phone',
                 models.CharField(blank=True,
                                  max_length=100,
                                  verbose_name='Phone number')),
                ('dob',
                 models.DateField(null=True, verbose_name='Date of Birth')),
                ('seat_preference',
                 models.CharField(choices=[('Window', 'Window seat'),
                                           ('Aisle', 'Aisle seat')],
                                  default=None,
                                  max_length=10,
                                  null=True,
                                  verbose_name='Seat Preference')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='user_profile',
                                   to='user.User')),
            ],
            options={
                'verbose_name_plural': 'User profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('image',
                 models.CharField(max_length=255,
                                  null=True,
                                  verbose_name='Passport')),
                ('passport_number',
                 models.CharField(max_length=100,
                                  null=True,
                                  verbose_name='Passport Number')),
                ('country',
                 models.CharField(max_length=255,
                                  null=True,
                                  verbose_name='Country of Citizenship')),
                ('issued_date',
                 models.DateField(null=True, verbose_name='Issued date')),
                ('expiry_date',
                 models.DateField(null=True, verbose_name='Expiry date')),
                ('profile',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='passport',
                                   to='user_profile.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'Passports',
                'db_table': 'user_passports',
            },
        ),
    ]
