# Generated by Django 2.2.2 on 2019-06-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20190619_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='country',
            field=models.CharField(max_length=255,
                                   null=True,
                                   verbose_name='Country of Citizenship'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='expiry_date',
            field=models.DateField(null=True, verbose_name='Expiry date'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='image',
            field=models.CharField(max_length=255,
                                   null=True,
                                   verbose_name='Passport Image URL'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='issued_date',
            field=models.DateField(null=True, verbose_name='Issued date'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='passport_number',
            field=models.CharField(max_length=100,
                                   null=True,
                                   unique=True,
                                   verbose_name='Passport Number'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='profile',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='passports',
                to='user_profile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=255,
                                   null=True,
                                   verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'),
                                            ('None', 'None')],
                                   default=None,
                                   max_length=10,
                                   null=True,
                                   verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=255,
                                   null=True,
                                   verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(max_length=255,
                                   null=True,
                                   verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=100,
                                   null=True,
                                   verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='seat_preference',
            field=models.CharField(choices=[('Window', 'Window seat'),
                                            ('Aisle', 'Aisle seat')],
                                   default=None,
                                   max_length=10,
                                   null=True,
                                   verbose_name='Seat Preference'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_profile',
                to='user.User'),
        ),
    ]
