# Generated by Django 2.2.2 on 2019-06-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20190620_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='passport_photo',
            field=models.CharField(
                default=
                'https://res.cloudinary.com/veeqtor/image/upload/v1561820733/airtech/user_photo_placeholder.png',
                max_length=255,
                verbose_name='Passport photograph'),
        ),
    ]
